name: millisecs
description: 'Converts various time formats to milliseconds and vice versa.'
version: 0.0.1
homepage: https://github.com/keepdeploying/millisecs

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
